import type { Metadata } from "next";
import {Roboto} from "next/font/google"

const font = Roboto({
  weight: '400',
  subsets: ['latin'],
})

import "./globals.css";
import Nav from "@/components/ui/Nav/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${font.className} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
